[package]
name = "macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.87", features = ["full"] }
aoc_core = { path = "../aoc_core" }
proc-macro2 = "1.0.89"
quote = "1.0.37"
lazy_static = "1.5.0"
anyhow.workspace = true
