[package]
name = "day_01"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
aoc_core.workspace = true
ctor.workspace = true
macros.workspace = true

[dev-dependencies]
predicates.workspace = true
pretty_assertions.workspace = true
