create day:
  #!/bin/bash
  cargo generate --path ./daily_template --name {{day}}
  cargo add -p {{day}} anyhow aoc_core ctor macros
  cargo add -p {{day}} --dev predicates pretty_assertions
  just get-input {{day}}

run day part:
  cargo run -q -p {{day}} -- {{part}}

get-input day:
  #!/bin/bash
  day_number=$(echo {{day}} | grep -o '[0-9]\+')
  aoc d -I -i {{day}}/input.txt -d $day_number -y 2015

